### ISSUE TITLE
(on event page) Link GUI "total events" "total errors" to values in event class

### ISSUE THREAD

**Issue by bcu8** [bradd07/Controller#11]

**Comment by bradd07** [comment]
QTextEdit is probably not the best solution for displaying this data as currently implemented

**Comment by zjp292** [comment]
Link update commands

**Comment by bradd07** [comment]
resolved with commit [98d1136](https://github.com/bradd07/Controller/commit/98d1136d518db017a491a5d55a021a12ce8f14c0)
