### ISSUE TITLE
Program output algorithms for event and error filtering options

### ISSUE THREAD

**Issue by bcu8** [bradd07/Controller#5]

**Comment by zjp292** [comment]
Eventfilter variable - enum of different filters
Correspond to event windows
Switch case to find events, errors, cleared, non clears and all (compare pointers)

**Comment by zjp292** [comment]
All events are the default for the filtering, move all events to default.

**Comment by bradd07** [comment]
resolved with commit [ac73d2d](https://github.com/bradd07/Controller/commit/ac73d2d71c867928a21b994df62baae9caa8d07f)
