### ISSUE TITLE
Electrical component class/data structure

### ISSUE THREAD

**Issue by bcu8** [bradd07/Controller#6]
Consider: serialize/deserialize ,dump/single message, csim message generation

**Comment by zjp292** [comment]
needed: 
serialize/de-serialize message, create the linked list (addNode, freeElectricalLL)

**Comment by zjp292** [comment]
Volts and amps, name wouldn't change
Electrical data is event dump 
At start it doesnt change
In csim, dump at beginning, then never touch it again
Gui display of electrical page
Add, free, display
Compare to status and events
